### ISSUE TITLE
Selecting None for PostgreSQL HyperScaler causes error 

### ISSUE THREAD

**Issue by JLeine** [vfarcic/crossplane-gh#24]
My Terminal Output if I select None
>▌ Which Hyperscaler do you want to use for PostgreSQL (select 'none' to continue without database)?
Error: stat examples/repo.yaml: no such file or directory

Which is correct since [examples](../tree/main/examples) does not contain a `repo.yaml` file

**Comment by JLeine** [comment]
Just saw that the file was [renamed here](https://github.com/vfarcic/crossplane-gh/commit/cd355f94923de3538622c98ccab300c6ef4b007e) so I've created the [initial file](https://github.com/vfarcic/crossplane-gh/commit/59235e4dd87ddf57f3f6604844bbd379e1768965#diff-9fb66730adbc352575bf8ed04e1351a1d334f6524c58e55a5f6affdfcebb8805) again on my fork and used it again. Then it works.

**Comment by JLeine** [comment]
Furthermore there is a follow up bug within [setup.sh](https://github.com/vfarcic/crossplane-gh/blob/main/setup.sh#L262) if you select None for PostgreSQL the var HYPERSCALER is set to None so the file `examples/repo-$HYPERSCALER.yaml` is not found either

**Comment by JLeine** [comment]
I also noticed that the ArgoCD Admin Password is somehow coming from [argo-cd.values](https://github.com/vfarcic/crossplane-gh/blob/main/argocd-values.yaml#L3) so I had to reset the password to gain access to the UI after port forwarding

```shell
kubectl -n argocd patch secret argocd-secret \            
  -p '{"data": {"admin.password": null, "admin.passwordMtime": null}}'
  
kubectl -n argocd rollout restart deployment argocd-server

kubectl -n argocd get secret argocd-initial-admin-secret \
  -o jsonpath="{.data.password}" | base64 -d
```

Not sure if that is intended?

**Comment by vfarcic** [comment]
> Just saw that the file was [renamed here](https://github.com/vfarcic/crossplane-gh/commit/cd355f94923de3538622c98ccab300c6ef4b007e) so I've created the [initial file](https://github.com/vfarcic/crossplane-gh/commit/59235e4dd87ddf57f3f6604844bbd379e1768965#diff-9fb66730adbc352575bf8ed04e1351a1d334f6524c58e55a5f6affdfcebb8805) again on my fork and used it again. Then it works.

That's my bad. I started working on it without the DB and later moved to the cases with DBs in AWS, GCP, and Azure and failed to go back and test the "no DB" scenario. I just made the changes to the repo but could not test them since I'm about to board a plane. Can you please take a look and let me know whether it is now okay?

**Comment by vfarcic** [comment]
> I also noticed that the ArgoCD Admin Password is somehow coming from [argo-cd.values](https://github.com/vfarcic/crossplane-gh/blob/main/argocd-values.yaml#L3) so I had to reset the password to gain access to the UI after port forwarding
> 
> ```shell
> kubectl -n argocd patch secret argocd-secret \            
>   -p '{"data": {"admin.password": null, "admin.passwordMtime": null}}'
>   
> kubectl -n argocd rollout restart deployment argocd-server
> 
> kubectl -n argocd get secret argocd-initial-admin-secret \
>   -o jsonpath="{.data.password}" | base64 -d
> ```
> 
> Not sure if that is intended?

I don't think I referenced the Argo CD UI anywhere so I did not explain what the password is. It's `admin123`. It should, obviously, not be used in production but for the demo it should be okay.

**Comment by JLeine** [comment]
Tested it and it works now 👍

**Comment by vfarcic** [comment]
Thanks for confirming it.
